# Generated by Django 5.2.4 on 2025-07-31 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StorageType',
        ),
        migrations.DeleteModel(
            name='StoreLocationType',
        ),
    ]
