# Generated by Django 5.2.4 on 2025-07-31 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_storagetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductStoreLocation',
        ),
    ]
