# Generated by Django 5.2.4 on 2025-08-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_rename_roles_to_employeerole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeerole',
            options={'verbose_name_plural': 'EmployeeRoles'},
        ),
    ]
